### ISSUE TITLE
Linter complains about `switch` indentation

### ISSUE THREAD

**Issue by janjaap** [Endouble/eslint-config#2]
Whenever I create a `switch` statement, like so:
```javascript
switch (event.data) {
    case YT.PlayerState.ENDED:
        console.warn('ended');
        break;
    case YT.PlayerState.PLAYING:
        console.warn('playing');
        break;
    default:
        console.warn('unknown event data');
        break;
}
```
the linter requires the indentation to be like this:
```javascript
switch (event.data) {
case YT.PlayerState.ENDED:
    console.warn('ended');
    break;
case YT.PlayerState.PLAYING:
    console.warn('playing');
    break;
default:
    console.warn('unknown event data');
    break;
}
```
which doesn't seem logic and also doesn't contribute to the readability. Is this a misconfiguration or is it intended?

**Comment by janjaap** [comment]
CC @koenknol, @rkedde, @Buchie, @jeroennicolai, @PaulinaEndouble, @druzina-nate, @leonardsmit, @StefNet

**Comment by renancouto** [comment]
@janjaap are you sure you are using this package and not the old config file? This was already pointed by @koenknol and have being available since the first version of this package:
```js
indent: ['error', 4, { SwitchCase: 1 }],
```

**Comment by koenknol** [comment]
@janjaap I don't have the issue with the switch anymore with this new eslint config. So i guess what renan said that you are using the old config.

**Comment by janjaap** [comment]
@koenknol, @renancouto Yes, I see. ProRail didn't have the dependency configured yet.
